"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-04-20 01:33:38.021090

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "news_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("pinned", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_news_items_pinned"), "news_items", ["pinned"], unique=False)
    op.create_index(
        op.f("ix_news_items_published_at"),
        "news_items",
        ["published_at"],
        unique=False,
    )
    op.create_table(
        "task_defs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "display_id",
            sqlmodel.sql.sqltypes.AutoString(length=16),
            nullable=False,
        ),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tag", sa.String(length=16), nullable=False),
        sa.Column("color", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("bonus", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("est_minutes", sa.Integer(), nullable=False),
        sa.Column("is_challenge", sa.Boolean(), nullable=False),
        sa.Column("cap", sa.Integer(), nullable=True),
        sa.Column("form_type", sa.String(length=16), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_task_defs_display_id"),
        "task_defs",
        ["display_id"],
        unique=True,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "display_id",
            sqlmodel.sql.sqltypes.AutoString(length=16),
            nullable=False,
        ),
        sa.Column(
            "email",
            sqlmodel.sql.sqltypes.AutoString(length=320),
            nullable=False,
        ),
        sa.Column("zh_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("en_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("nickname", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("phone_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("line_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("telegram_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("avatar_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("profile_complete", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_display_id"), "users", ["display_id"], unique=True)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "rewards",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("task_def_id", sa.Uuid(), nullable=False),
        sa.Column("task_title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("bonus", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("earned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_def_id"],
            ["task_defs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rewards_task_def_id"), "rewards", ["task_def_id"], unique=False)
    op.create_index(op.f("ix_rewards_user_id"), "rewards", ["user_id"], unique=False)
    op.create_table(
        "task_def_requires",
        sa.Column("task_def_id", sa.Uuid(), nullable=False),
        sa.Column("requires_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["requires_id"],
            ["task_defs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_def_id"],
            ["task_defs.id"],
        ),
        sa.PrimaryKeyConstraint("task_def_id", "requires_id"),
    )
    op.create_table(
        "task_progress",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("task_def_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("progress", sa.Float(), nullable=True),
        sa.Column("form_submission", sa.JSON(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_def_id"],
            ["task_defs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "task_def_id", name="uq_progress_user_task"),
    )
    op.create_index(
        op.f("ix_task_progress_task_def_id"),
        "task_progress",
        ["task_def_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_progress_user_id"),
        "task_progress",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "task_step_defs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_def_id", sa.Uuid(), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_def_id"],
            ["task_defs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_def_id", "order", name="uq_step_order"),
    )
    op.create_index(
        op.f("ix_task_step_defs_task_def_id"),
        "task_step_defs",
        ["task_def_id"],
        unique=False,
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "display_id",
            sqlmodel.sql.sqltypes.AutoString(length=16),
            nullable=False,
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("alias", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("topic", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("leader_id", sa.Uuid(), nullable=False),
        sa.Column("cap", sa.Integer(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("week_points", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["leader_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_teams_display_id"), "teams", ["display_id"], unique=True)
    op.create_index(op.f("ix_teams_leader_id"), "teams", ["leader_id"], unique=True)
    op.create_table(
        "join_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_join_requests_team_id"),
        "join_requests",
        ["team_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_join_requests_user_id"),
        "join_requests",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "task_step_progress",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("step_id", sa.Uuid(), nullable=False),
        sa.Column("done", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["task_step_defs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "step_id", name="uq_step_progress_user_step"),
    )
    op.create_index(
        op.f("ix_task_step_progress_step_id"),
        "task_step_progress",
        ["step_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_step_progress_user_id"),
        "task_step_progress",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "team_memberships",
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("team_id", "user_id"),
        sa.UniqueConstraint("user_id", name="uq_membership_user"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("team_memberships")
    op.drop_index(op.f("ix_task_step_progress_user_id"), table_name="task_step_progress")
    op.drop_index(op.f("ix_task_step_progress_step_id"), table_name="task_step_progress")
    op.drop_table("task_step_progress")
    op.drop_index(op.f("ix_join_requests_user_id"), table_name="join_requests")
    op.drop_index(op.f("ix_join_requests_team_id"), table_name="join_requests")
    op.drop_table("join_requests")
    op.drop_index(op.f("ix_teams_leader_id"), table_name="teams")
    op.drop_index(op.f("ix_teams_display_id"), table_name="teams")
    op.drop_table("teams")
    op.drop_index(op.f("ix_task_step_defs_task_def_id"), table_name="task_step_defs")
    op.drop_table("task_step_defs")
    op.drop_index(op.f("ix_task_progress_user_id"), table_name="task_progress")
    op.drop_index(op.f("ix_task_progress_task_def_id"), table_name="task_progress")
    op.drop_table("task_progress")
    op.drop_table("task_def_requires")
    op.drop_index(op.f("ix_rewards_user_id"), table_name="rewards")
    op.drop_index(op.f("ix_rewards_task_def_id"), table_name="rewards")
    op.drop_table("rewards")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_display_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_task_defs_display_id"), table_name="task_defs")
    op.drop_table("task_defs")
    op.drop_index(op.f("ix_news_items_published_at"), table_name="news_items")
    op.drop_index(op.f("ix_news_items_pinned"), table_name="news_items")
    op.drop_table("news_items")
    # ### end Alembic commands ###
