import type { Task, MockMember, MockTeam } from './types';

export const TASKS: Task[] = [
  {
    id: 1,
    title: "填寫金富有志工表單",
    due: null,
    daysLeft: null,
    color: "#fec701",
    points: 50,
    tag: "探索",
    bonus: null,
    status: "completed",
    summary: "完成你的志工個人資料，開啟金富有志工旅程。",
    description:
      "歡迎加入金富有志工！請填寫基本個人資料，讓我們了解你的興趣、專長與可投入時段，並協助系統為你推薦合適的任務與團隊。",
    estMinutes: 5,
    steps: [
      { label: "確認電子郵件與手機", done: true },
      { label: "填寫個人興趣與專長", done: true },
      { label: "選擇可投入的時段", done: true },
      { label: "簽署志工服務同意書", done: true },
    ],
  },
  {
    id: 2,
    title: "夏季盛會報名",
    due: "2026-04-30",
    daysLeft: 12,
    color: "#8AD4B0",
    points: 100,
    tag: "社区",
    bonus: "限定紀念徽章",
    status: "in_progress",
    progress: 0.4,
    summary: "為即將到來的夏季盛會報名，鎖定你的服務崗位。",
    description:
      "夏季盛會將於 5 月 10 日舉行，需要大量志工支援現場。完成報名後，你可以選擇服務崗位（接待、導覽、物資、秩序）並與組長對接行前細節。",
    estMinutes: 10,
    steps: [
      { label: "填寫報名表", done: true },
      { label: "選擇服務崗位", done: true },
      { label: "參加行前說明會", done: false },
      { label: "領取志工識別證", done: false },
      { label: "確認當日到場時間", done: false },
    ],
  },
  {
    id: 3,
    title: "組隊挑戰",
    due: "2026-04-30",
    daysLeft: 12,
    color: "#fed234",
    points: 200,
    tag: "陪伴",
    bonus: "金鑰匙紀念筆",
    status: "todo",
    requires: [1, 2],
    cap: 6,
    teamProgress: null,
    isChallenge: true,
    summary: "組建至少 6 人志工團隊，一起挑戰進階任務。",
    description:
      "招募夥伴加入你的團隊（你是隊長），或申請加入朋友的團隊。截止日前團隊成員數達 6 人即可獲得獎勵，人數不設上限。",
    estMinutes: 30,
  },
  {
    id: 4,
    title: "春季志工培訓",
    due: "2026-04-10",
    daysLeft: -8,
    color: "#B8A4E3",
    points: 30,
    tag: "探索",
    bonus: null,
    status: "expired",
    summary: "春季志工基礎培訓，錯過此梯次可於秋季再報名。",
    description:
      "此為每年春季固定舉辦的志工基礎培訓，內容包含志工倫理、安全守則、服務禮儀等。本梯次已於 4 月 10 日結束報名，請留意秋季場次。",
    estMinutes: 90,
    steps: [
      { label: "完成線上報名", done: false },
      { label: "出席培訓課程", done: false },
      { label: "通過結業測驗", done: false },
    ],
  },
];

export const MOCK_MEMBERS: MockMember[] = [
  {
    id: "u1",
    name: "林詠瑜",
    role: "設計美編",
    avatar: "linear-gradient(135deg, #fed234, #fec701)",
  },
  {
    id: "u2",
    name: "陳志豪",
    role: "影像剪輯",
    avatar: "linear-gradient(135deg, #fec701, #B8A4E3)",
  },
  {
    id: "u3",
    name: "王美玲",
    role: "活動企劃",
    avatar: "linear-gradient(135deg, #8AD4B0, #fec701)",
  },
  {
    id: "u4",
    name: "張書豪",
    role: "外語·翻譯",
    avatar: "linear-gradient(135deg, #fed234, #fed234)",
  },
  {
    id: "u5",
    name: "李佳穎",
    role: "文案寫作",
    avatar: "linear-gradient(135deg, #FFD6A8, #fed234)",
  },
  {
    id: "u6",
    name: "黃宇軒",
    role: "攝影紀錄",
    avatar: "linear-gradient(135deg, #B8A4E3, #8AD4B0)",
  },
  {
    id: "u7",
    name: "吳雅萱",
    role: "接待導覽",
    avatar: "linear-gradient(135deg, #fec701, #fec701)",
  },
  {
    id: "u8",
    name: "蔡承恩",
    role: "資料分析",
    avatar: "linear-gradient(135deg, #fec701, #8AD4B0)",
  },
];

export const MOCK_TEAMS: MockTeam[] = [
  {
    id: "T-MING2024",
    name: "星河守望隊",
    leader: "周明蓁",
    leaderId: "UMING",
    topic: "長者陪伴",
    members: 3,
    cap: 5,
    points: 1840,
    weekPoints: 280,
    rank: 3,
    leaderAvatar: "linear-gradient(135deg, #fed234, #fec701)",
  },
  {
    id: "T-WEI8810",
    name: "光點行動組",
    leader: "許子瑋",
    leaderId: "UWEI",
    topic: "社區導覽",
    members: 4,
    cap: 5,
    points: 2120,
    weekPoints: 360,
    rank: 2,
    leaderAvatar: "linear-gradient(135deg, #fec701, #B8A4E3)",
  },
  {
    id: "T-TING0517",
    name: "綠意日常",
    leader: "鄭宜庭",
    leaderId: "UTING",
    topic: "環境關懷",
    members: 2,
    cap: 4,
    points: 960,
    weekPoints: 140,
    rank: 5,
    leaderAvatar: "linear-gradient(135deg, #8AD4B0, #FFD6A8)",
  },
  {
    id: "T-CHU1109",
    name: "童心共讀",
    leader: "劉雅筑",
    leaderId: "UCHU",
    topic: "兒童陪讀",
    members: 5,
    cap: 5,
    points: 2680,
    weekPoints: 420,
    rank: 1,
    leaderAvatar: "linear-gradient(135deg, #fed234, #FFD6A8)",
  },
];
